### ISSUE TITLE
Utiliser les options d'accrochage définies dans le projet pour les outils : interpolate, duplicate line, move and copy, extrapolate

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#1]
Les outils d'édition spécifiques " interpolate, duplicate line, move and copy, extrapolate" devraient pouvoir utiliser les options d'accrochage du projet (QGIS) définies par l'utilisateur. 
Cependant, l'accrochage devrait être actif uniquement sur des couches visibles sur la carte.  
Si pour un outil d'édition, une option d'accrochage est indispensable, l'utilisateur doit recevoir un message d’avertissement. (par ex.: aucun accrochage actif sur la couche )

**Comment by dsavary** [comment]
Par ailleurs, pour l'outil "interpolate", le symbole d'accrochage devrait réagir différemment selon les cas de figure  suivant : 
- Intersection entre 2 couches -> symbole croix
- Accrochage sur un vertex -> symbole rond
- Accrochage "proche" sur un segment -> symbole "sablier" (deux triangles un par dessus l'autre)

**Comment by gusthiot** [comment]
Fait
