### ISSUE TITLE
Améliorer l'interface graphique de l'outil de profil

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#10]
Marge autour du graphique (pour bien voir les points sur les bords et hauteurs du profil)
Indiquez une légende et l'unité pour les 2 axes du graphique
Rendre le label du numéro de vertex plus lisible
Ouvrir le graphique en mode "Matplotlib" par défaut

**Comment by dsavary** [comment]
Indiquer dans la légende uniquement les couches de points visibles et utilisés dans le graphique du profil
Ajouter un symbole "point" avec le texte
Proposer uniquement les couches de points se trouvant sur la ligne de référence du profil
Le numéro du vertex de la ligne de s'affiche pas dans le graphique
Le symbole du suivi de le long du profil ne fonctionne plus.

**Comment by gusthiot** [comment]
Ok pour Qwt5 ?
