### ISSUE TITLE
Fonctionnement de l'outil "profil"

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#11]
L'outil ne permet de modifier l'altitude interpolée du vertex de la ligne ou du point si les couches ne sont pas en édition au préalable.
Il faudrait automatiquement basculer les couches en édition si l'utilisateur désire effectuer la correction par interpolation.
L'utilisateur doit pouvoir valider les modifications (clic sur Enregistrer) ou annuler en cas de mauvaises manipulations.

**Comment by gusthiot** [comment]
Fait. A tester

**Comment by dsavary** [comment]
Option supplémentaire de l'outil de profil : il serait judicieux de disposer d'une indication de contrôle sur l'altitude (vertex) des conduites qui sont connectés (adjacente) aux conduites sélectionnés pour la création du profil.
Cela permettrait de vérifier l'altitude des conduites qui sont connectées entre elles.
2 cas de connection : conduites connectées à une nœud commun (intersection) et conduites connectées à un vertex commun.

**Comment by gusthiot** [comment]
Fait. A tester
