### ISSUE TITLE
Outil "intersect" , utiliser une géométrie de type cercle pour définir la cote

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#12]
Si possible, il serait plus optimal d'utiliser une géométrie de type "cercle" qu'une polyligne avec une quantité de petits segments
Lors de la définition de la distance, mettre 6m par défaut et donner la possibilité à l'utilisateur de donner directement la distance au clavier (éviter de devoir sélectionner le champ pour définir la distance)

**Comment by gusthiot** [comment]
Fait. A tester.
Pour info, le circularstring de qgis est construit comme le circularstring de postgis, c'est-à-dire à partir de 4 points (nord, sud, est, ouest).

**Comment by dsavary** [comment]
Ok pour les cercles
Bug - régler le plantage de QGIS lors de l'utilisation de cet outil (version 2.16 et 2.14)

**Comment by dsavary** [comment]
Amélioration : Concernant l'outil "intersect", il serait bien de pouvoir sauver la valeur de la cote (distance) dans un attribut "distance" de la couche "Memory layer". Cette info peut ainsi être utilisé comme étiquette et directement visible pour l'utilisateur

**Comment by gusthiot** [comment]
fait
