### ISSUE TITLE
Utilisation uniquement des points 3D positionnés sur les vertex des lignes sélectionnées pour l'outil de profil

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#13]
Redéfinir une tolérance plus petite pour les points se trouvant sur la ligne 3D. 
Fixer la tolérance à 3cm.

**Comment by gusthiot** [comment]
Fait. A tester.

**Comment by dsavary** [comment]
Problème d'activation et désactivation de l'outil. 
- Ferme la fenêtre de profil -> déactive l'outil et désélectionne la ligne concernée, mais impossible de réactiver l'outil
- Clic sur l'outil "profil" permet de relancer la calcul d'un profil (déselection + effacer le graphique.
- Permettre resélectionner une ou plusieurs lignes pour recalculer un autre profil sans désactiver entièrement l'outil.

**Comment by gusthiot** [comment]
Toujours un problème ?
