### ISSUE TITLE
Outil "duplicate line"

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#14]
comportement anormal lors de la sélection d'une polyligne 3D
Mettre par défaut en mode "sélection" la distance de décalage que l'utilisateur doit insérer

**Comment by gusthiot** [comment]
1) des précisions ?
2) fait

**Comment by dsavary** [comment]
Amélioration: ajouter un "bouton" (case à cocher) pour inverser le coté sur lequel se dessine la ligne dupliquée (change la valeur en négatif ou positif)

**Comment by gusthiot** [comment]
fait
