### ISSUE TITLE
Please add a more comprehensive explanation in the About

### ISSUE THREAD

**Issue by pcav** [gusthiot/VDLTools#15]
So users and developers can understand whether this can be useful for them.

**Comment by gusthiot** [comment]
Is it ok like that ?

**Comment by pcav** [comment]
Very good, thanks.
These seem important tools of very general usage, why not adding them directly to Processing?

**Comment by gusthiot** [comment]
I'm not on QGIS since very long, and more as plugin developper than user. I don't know the processing part. How to use it and how easy it is to add something to it.
But what I know is that some tools of our plugin will be available in the core in QGIS 3. Until that, we need a plugin to do it on QGIS 2...

**Comment by pcav** [comment]
Could you please discuss this on qgis-dev ML?
Sorry to bother, but we are trying hard to consolidate and reduce redundancy in plugins, for several we believe good reasons.
Thanks.

**Comment by gusthiot** [comment]
I had a look on the Processing part, and I'm not sure to understand the goal to add some DAO tools (for the most part) in batch processes, and to take in account for consolidation a plugin that aims to disapear (or change a lot) when QGIS 3 will become available.
Could you please give more explanations ? Because now I'm not able to determine a subject for a ML question...

**Comment by pcav** [comment]
If you believe this is only a temporary tool, we can publish it as such. However, it seemed to me some of the tools are valuable and of general use, and could be profitably integrated in more complex modelling. Moving it to Processing would also make your life easier, as you will not need to write the GUI for it.

**Comment by gusthiot** [comment]
To resume tool by tool : 
- duplicate will be included in QGIS 3
- copy/move will be included in QGIS 3
- profile : different projects are working on line profile, in the future a consolidation will be done
- intersect : extends another tool for curved objects
- interpolation/extrapolation : very few tools available in QGIS using the elevation, those could be kept, but I don't know how to use it in processing as soon as we have to point on the map
- import : specific tool to import data in the data model of Ville de Lausanne

So, from my point of view, I don't know what to put in Processing, but I'm no Processing expert...

**Comment by pcav** [comment]
I'd suggest to move only intersect and interpolation/extrapolation to Processing, if feasible, and leave the rest of the plugin as it is.
If I understand correctly, you can use the new widget to point on the map for the int/ex tool.
However, I do not want to bother too much, if you think it is better to publish it as it is, pending further improvements and integrations, I'm fine with this.
Thanks for understanding.

**Comment by gusthiot** [comment]
If you agree, I'd prefer to publish it like that for now. And then, I'm fine to dig into the Processing part to see how to migrate part of the plugin to it.

**Comment by pcav** [comment]
Done.

**Comment by gusthiot** [comment]
Thanks !

**Comment by gusthiot** [comment]
Hi,
Hum, apparently the plugin installation through QGIS is not working. I have a "corrupted extension : invalid syntax" issue. Package name and directory name seem to be the same. Know why ?

**Comment by pcav** [comment]
Not really, please refe to qgis-dev ML.
Thanks.
