### ISSUE TITLE
Outil « Profil » : aspect graphique

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#19]
Affichage du profil – aspect graphique :
•	Problème de légende lors de la génération d’un PDF (librairie Qwt5) – pas de légende et images toutes serrées
•	Qualité de l’export (pixelisé) : Peut-on obtenir mieux ? 
•	Il manque la légende sur les axes (librairie Mapplotlib)
•	Légende « conduiteconnecté » à corriger : conduites connectées
•	Le profil du MNT et MNS n’est pas de la même longueur que le profil de la conduite ?

**Comment by gusthiot** [comment]
- à étudier
- très compliqué
- fait
- fait
- exact, cela dépend des points pris en compte par le générateur de MN

**Comment by dsavary** [comment]
pour le premier point : 

-  on garde si possible l'ancienne méthode d'export de graph pour le format PDF (on garde ainsi une bonne qualité.
- Pour l'export PNG, on maintient le fonctionnement actuel.

Les autres points : ok

**Comment by gusthiot** [comment]
Fait

**Comment by dsavary** [comment]
Ok merci
