### ISSUE TITLE
Outil « Move » : Outil pour déplacer ou copier un objet sélectionné

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#20]
Lorsque l’accrochage est actif au niveau des sommets et des segments sur la couche, le symbole « carré » n’est pas visible, mais l’accrochage fonctionne bien. Le symbole « carré » est visible uniquement pour un accrochage sur la propre sélection.

**Comment by dsavary** [comment]
Non prioritaire : Est-ce qu’on pourrait imaginer assez facilement étendre le fonctionnement de cet outil pour que la copie ou le déplacement soient possible pour une sélection de plusieurs objets de couches différentes ?

**Comment by gusthiot** [comment]
Problème d'accrochage réglé

**Comment by dsavary** [comment]
magnifique
