### ISSUE TITLE
Outil «  Multi-Select » : Sélection multiple entre couche et ouverture automatique des tables attributaires selon la sélection

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#21]
Une erreur apparaît suite au déclenchement de l’outil : 

> AttributeError: 'MultiAttributesTool' object has no attribute '_MultiselectTool__first' 
Traceback (most recent call last):
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\multiselect_tool.py", line 50, in __select
    searchRect = QgsRectangle(self.__first, self.__last)
AttributeError: 'MultiAttributesTool' object has no attribute '_MultiselectTool__first'

**Comment by gusthiot** [comment]
Fait

**Comment by dsavary** [comment]
ok . 
Non priotitaire : ouvrir le tableau des attributs avec le mode de filtre "objets sélectionnés et non l'utilisation d'uun filtre avec $id IN (...)

**Comment by dsavary** [comment]
ok, nouvelle issue #28 créée pour le dernier point. 
Prochaine version du plugin
