### ISSUE TITLE
Outil « Import » : Import des mesures de terrain en tant qu’objet du réseau selon une configuration prédéfinie

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#22]
Lors de l’utilisation de cet outil, nous obtenons l’erreur suivante : 

> AttributeError: 'NoneType' object has no attribute 'clicked' 
Traceback (most recent call last):
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\import_measures.py", line 158, in start
    self.__jobsDlg.pointsRadio().clicked.connect(self.__onPointsRadio)
AttributeError: 'NoneType' object has no attribute 'clicked'

**Comment by gusthiot** [comment]
Fait

**Comment by dsavary** [comment]
L'erreur apparaît lorsque QGIS doit retourner une erreur "postgres" et que la console Python n'a pas été ouverte au préalable : 

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 213: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\import_measures.py", line 270, in __confirmAndNext
    self.__nextCheck()
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\import_measures.py", line 274, in __nextCheck
    self.__checkIfExist()
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\import_measures.py", line 250, in __checkIfExist
    self.__insert()
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\import_measures.py", line 311, in __insert
    print(query2.lastError().text())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 213: ordinal not in range(128)

Si la console Python a été ouverte au préalable , l'erreur ci-dessus ne s'affiche pas.

Est-ce que l’erreur peut être affichée dans la bar des messages pour éviter ce problème ?

**Comment by dsavary** [comment]
Gestion des logs / erreur: 
- il faudrait prendre en compte le fait que si une mesure ne possède pas "code" ou un code erroné , un message est renvoyé à l'utilisateur, lui indiquant que le code du point est non valable et par conséquent la mesure n'est pas traitée. 
- Il faut tester que que la ligne de mesure possède un code qui est bien défini dans la table de configuration d'import "usr_import_config". ( code in SELECT DISTINCT code FROM usr_import_config)

**Comment by dsavary** [comment]
Dans le code, je proposerai une petit modification : 
`query = self.__db.exec_("""SELECT code,description,geometry,id,usr_session_name FROM """ + self.__sourceTable +
                                """ WHERE """ + condition + """ AND usr_valid = FALSE""")`
J'ajouterais à la requête l'attribut "usr_fk_table" qui donne l'identifiant de la table concernée.

Le nom "officiel" de la table serait récupéré à ce niveau : 
`query2 = self.__db.exec_(
                    """SELECT id, schema FROM qwat_sys.doctables WHERE name = '""" + data['descr'] + """'""")`

-> SELECT id, schema, name, name_fr FROM qwat_sys.doctables WHERE id =  '""" + data['usr_fk_table'] + """'

**Comment by gusthiot** [comment]
Fait

**Comment by dsavary** [comment]
en ordre
