### ISSUE TITLE
Outil «  extrapole » : comportement lorsque le segment est trop grand pour appliquer une interpolation

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#24]
Donner la valeur interpolée même si le segment est trop grand, L'utilisateur a alors la possibilité d’accepter ou non la valeur interpolée proposée (boite de dialogue pour confirmation)

**Comment by gusthiot** [comment]
Fait

**Comment by dsavary** [comment]
Ok merci pour la modification.
On peut clore l'issue
