### ISSUE TITLE
Fonctionnement avec des couches de type "shapefile", "memory layer", "postgis" 

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#3]
Fonctionnement avec des couches de divers fournisseurs de données, principalement des formats standard utilisé dans QGIS. Pour les outils d'édition suivant : 
1) interpolate, duplicate, move, intersect  : shapefile, memory layer, postgis
2) extrapolate, profil tool : shapefile, postgis

Effectuer des tests pour voir si cela fonctionne bien.

**Comment by gusthiot** [comment]
Ca joue chez moi
