### ISSUE TITLE
Erreur python - outils profil

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#30]
Une erreur python apparaît lors de l'utilisation de l'outil "profil". Elle apparaît lorsque : 
2 points de couches différentes se trouvent à la même position XY
avec des altitudes différentes ou égales 
et se trouvant sur un vertex de la ligne 3d sélectionné. 
Par ex. altitude de la mesures et altitude de l'objet du réseau (élément de montage, vanne,... ) sur un vertex de la conduite (dans l'exemple vertex 10,11,13 et 15).

![profil3d_1](https://user-images.githubusercontent.com/6229296/31375372-967d52de-ada1-11e7-9311-c688e1a0cbc9.png)
![profil3d_2](https://user-images.githubusercontent.com/6229296/31375376-98b15370-ada1-11e7-9606-738c6f8d579d.png)
![profil3d_3](https://user-images.githubusercontent.com/6229296/31375382-9a97e758-ada1-11e7-8137-6eebe1e44836.png)

L'erreur survient au moment de cliquer sur le bouton "appliquer l'altitude du point à la ligne " 
L'utilisateur doit choisir une des 2 solutions pour le vertex en question (coché la solution à utiliser)

A développer: avertissement à l'utilisateur qu'il y a 2 solutions d'altitude pour le même vertex de la ligne.
avant de pour suivre le calcul et la correction des altitudes.

**Comment by dsavary** [comment]
Si l'altitude sur le même vertex est identique , l'utilisateur n'a pas besoin de faire de choix, l'altitude "identique" des points est appliquée à la ligne.

**Comment by gusthiot** [comment]
Fait.
Quelle précision pour "identique" ?

**Comment by dsavary** [comment]
Les coordonnées en planimétrie et en altimétrie doivent être identiques au mm. 
Sinon, on considère que c'est 2 points.

**Comment by gusthiot** [comment]
Fait.

**Comment by dsavary** [comment]
Testé. ça fonctionne bien. 
Merci
