### ISSUE TITLE
Outil profil: lignes ou "conduites" connectées , détection même si aucun vertex commun

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#35]
Problème lors de la détection de conduites connectées: 
Sélection 1 : 
![profil_conduites_connectees](https://user-images.githubusercontent.com/6229296/33824602-439a5da2-de5f-11e7-8ffb-8c8154afe2e4.PNG)
L'outil ne détecte que les extrémités de la conduite verte où il y a bien une connectivité entre vertex.
Sélection 2 : 
![profil_conduites_connectees_conduite2](https://user-images.githubusercontent.com/6229296/33824680-7a6a75c4-de5f-11e7-9403-485a4e32df32.PNG)
L'outil détecte une conduite connectée au point 4, alors qu'il n'y a pas de vertex en commun, alors que sur la première sélection, il ne voit pas cette connectique. 
La détection d'une conduite connectée ne devrait se faire que s'il y a un vertex commun. (connectivité entre vertex). Est-ce possible d'intégrer ceci dans l'outil de profil ?

illustration des vertex de la conduite : 
![profil_conduites_connectees_vertex](https://user-images.githubusercontent.com/6229296/33825148-f9cf75c0-de60-11e7-905d-6f67ec9486f5.PNG)

**Comment by dsavary** [comment]
Autre exemple, plus simple: 
![ex2_selection1](https://user-images.githubusercontent.com/6229296/33825077-bc5f49d6-de60-11e7-9834-2839a150488b.PNG)
pas de détection de la conduite connectée, ok
![ex2_selection2](https://user-images.githubusercontent.com/6229296/33825080-be679bac-de60-11e7-9043-0e1c84606fda.PNG)
détection de la conduite connectée, alors qu'un aucun vertex commun.

**Comment by gusthiot** [comment]
J'ai fait une correction, tu me diras si cela résout le problème.

**Comment by dsavary** [comment]
Testé, ça me semble tout bon. Affichage dans le profil des lignes connectées uniquement si il existe un  vertex commun entre les 2 lignes 3D.
