### ISSUE TITLE
Profil tool : bug lorsqu'une ligne 3D possède des vertex "double" 

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#37]
@gusthiot 

Bug sur l'outil de profil lorsque qu'une ligne possède des vertex double, c'est à dire 2 sommets (pair de coordonnées) à la même position 2D sur la ligne. 
En principe, il ne devrait pas exister des polylignes avec des vertex dupliqués, ceci est une erreur de géométrie. Cependant, l'outil de profil interprète des vertex double comme des points individuels et ceci pose problème dans l'utilisation de l'outil. Un des effets "secondaires" est qu'il propage l'altitude de points superposés sur les mauvais vertex de la ligne. 
Voir démo gif ci-dessous : 
![vertex_double_ligne_profil_bug](https://user-images.githubusercontent.com/6229296/41234291-4761eb52-6d7b-11e8-8696-791ca520fbb6.gif)

**Description  de l'exemple :** 
une ligne 3D composée de 5 vertex dont un doublon au 2e et 3e vertex. (normalement elle ne devrait en avoir 4 uniquement)
La génération du profil n'identifie pas ce doublon, ceci peut paraître normal.
Cependant, lorsqu'on applique l’altitude des points (2 pts à avec un Z à 500m), l'altitude est modifiée sur le 2e et 3e vertex (le doublon) et non sur le 4e vertex. 

Il faudrait donc corriger cet outil afin que ce bug ne se reproduise et avertissent l'utilisateur : 
Un message d'alerte apparaît au moins de générer le profil indiquant à l'utilisateur que la polyligne possède des vertex avec les mêmes coordonnées (doublons ou plus...) .
L'utilisateur corrige le cas et relance le profil. 
Ou sinon, on peut faire en sorte que l'outil génère la séquence des vertex de manière s'il identifie qu'ils ont les mêmes coordonnées, mais à mon avis, cette piste est plus complexe et risque de poser d'autres problèmes.

**Comment by gusthiot** [comment]
Ainsi ?

**Comment by dsavary** [comment]
Merci pour la correction :) 
Deux remarques : 
Est-il possible d'avoir le message en Français ? Je mettrais le texte : " Attention ! La ligne ID XXX possède 2 sommets identiques sur le vertex ID XXXX (mêmes coordonnées X et Y). Veuillez corriger la géométrie de la ligne " 
Je mettrais l'avertissement dans une boite de dialogue afin que l'utilisateur est bien lu l'avertissement et doive cliquer sur OK pour passer à la suite.
On peut en discuter demain.

**Comment by gusthiot** [comment]
J'ai corrigé pour la traduction, cela joue ?

**Comment by dsavary** [comment]
Oui , nickel merci !

**Comment by dsavary** [comment]
effet de bord sur la correction du double vertex sur une ligne.
L'erreur apparaît à chaque fois qu'on désire faire des profils sur plusieurs lignes d'un seul coup. 
voici la démo sur des lignes 3D corrects au niveau géométrique. 

![bug_correction_dble_vertex_multiselection](https://user-images.githubusercontent.com/6229296/44835038-2a6e9580-ac33-11e8-8e90-9698bac7bbf1.gif)
L'erreur apparaît lors d'une sélection multiple.
Peux-tu corriger ceci  ?

**Comment by dsavary** [comment]
testé et validé
