### ISSUE TITLE
sélection impossible sur le premier objet d'une couche shp avec les outils VDLtools

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#38]
Les outils VDLtools qui demande une sélection d'un objet ne fonctionne pas sur le premier objet d'un fichier shp. 
outils concernés : 
- profil tool
- copy/move
- duplicate
- interpolate
- extrapolate

voir démo : 

![vdltool_tools_selection](https://user-images.githubusercontent.com/6229296/45102083-2825a300-b12d-11e8-974c-81924b19622c.gif)

**Comment by gusthiot** [comment]
Corrigé

**Comment by dsavary** [comment]
testé ok
