### ISSUE TITLE
Ouverture du formulaire personnalisé d'édition des attributs

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#4]
Le formulaire pour éditer les attributs doit s'ouvrir selon le paramétrage défini dans les propriétés de chaque couche lors de l'utilisation des outils suivants : 
interpolate, duplicate , copy 
En cas de couche lié à une base de données (PostGIS), l'incrémentation de la séquence doit se faire sur la clé primaire (id) pour éviter une erreur lors de l'insertion.

**Comment by gusthiot** [comment]
A tester ^^

**Comment by dsavary** [comment]
EN priorité pour l'outil "interpolate", il serait judicieux de prendre en compte le fait que le formulaire de saisie s'affiche ou non lors de la création de l'entité. Pour certains objets, cette valeur est renseigné à "On" afin que l'édition des attributs se fassent en masse à la fin de la saisie géométrique. Cet info se trouve dans les propriétés de la couche.

**Comment by gusthiot** [comment]
Fait, pour interpolate, move et duplicate
