### ISSUE TITLE
QGIS 3 VDLTools - interpolate

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#43]
@ je t'envoie les erreurs obtenues après quelques tests avec QGIS 3

sur l'outil Interpolate :

![image](https://user-images.githubusercontent.com/6229296/68943025-54fe2d00-07aa-11ea-8877-73ae376d6476.png)

**Comment by dsavary** [comment]
Une autre
![image](https://user-images.githubusercontent.com/6229296/68945523-deb0f900-07b0-11ea-864e-b31ee23f2815.png)

**Comment by gusthiot** [comment]
Devrait marcher maintenant

**Comment by dsavary** [comment]
Nouvelle erreur sur QGIS 3 

Une idée ?

![error_interpolate_vdltools](https://user-images.githubusercontent.com/6229296/74040479-1b614a80-49c4-11ea-8825-fc87e0e8b5cc.PNG)

**Comment by dsavary** [comment]
J'ai eu celle-ci aussi en changeant d'outil de "extrapolate" à "Interpolate"

![error_change_tools_vdltools](https://user-images.githubusercontent.com/6229296/74041000-2072c980-49c5-11ea-9792-f7e31d4067cb.PNG)

**Comment by gusthiot** [comment]
> J'ai eu celle-ci aussi en changeant d'outil de "extrapolate" à "Interpolate"
> 
> ![error_change_tools_vdltools](https://user-images.githubusercontent.com/6229296/74041000-2072c980-49c5-11ea-9792-f7e31d4067cb.PNG)

Tu n'aurais pas utilisé le plugin de reload un moment avant ? Parce qu'en général c'est comme ça que j'obtiens un layer = NoneType...

**Comment by gusthiot** [comment]
> Nouvelle erreur sur QGIS 3
> 
> Une idée ?
> 
> ![error_interpolate_vdltools](https://user-images.githubusercontent.com/6229296/74040479-1b614a80-49c4-11ea-8825-fc87e0e8b5cc.PNG)

Corrigé

**Comment by dsavary** [comment]
Je n'ai plus d'erreurs, cependant je remarque un problème sur les valeurs par défaut de certains attributs dans les formulaires si on crée l'objet avec l'outil standard QGIS "crééer une entité" ou avec "Interpolate"

Par ex. : pour l'ID de la couche, QGIS fait un nextval pour la valeur par défaut.
Avec créer une entité, on a un nextval et la contrainte non null est respecté (coche verte, ok)

![error_interpolate_vdltools_form1](https://user-images.githubusercontent.com/6229296/74133144-34e2dc00-4be8-11ea-9173-ac426ced8969.PNG)

Avec l'outil "interpolate", on voit le nextval, mais à mon avis, le formulaire n'a pas de valeur saisie, du coup, la contrainte non null n'est pas respectée et on a une croix sur l'attribut. 

![error_interpolate_vdltools_form2](https://user-images.githubusercontent.com/6229296/74133152-37ddcc80-4be8-11ea-99c7-697ef26fe659.PNG)

Je me rappelle que l'on avait déjà du faire qqch sur QGIS 2. 

Ci-dessous, le propriété de la couche pour l'attribut ID:
 
![error_interpolate_vdltools_form_propriete](https://user-images.githubusercontent.com/6229296/74133195-50e67d80-4be8-11ea-911e-4d4e35653b81.PNG)

**Comment by gusthiot** [comment]
On a en effet quelque chose d'assez complexe qui permet, après avoir déterminé la géométrie du point, d'ajouter tous les attributs avec leur valeur par défaut :

`pt_feat = QgsFeature(self.__layer.fields())`
           ` pt_feat.setGeometry(QgsGeometry(vertex))`
        `    for i in range(len(self.__layer.fields())):`
         `       e = QgsExpression(self.__layer.defaultValueDefinition(i).expression())`
        `        c = QgsExpressionContext()`
         `       c.setFeature(pt_feat)`
         `       default = e.evaluate(c)`
         `       pt_feat.setAttribute(i, default)`

Cela fonctionne dans QGIS 2.18 en mettant nextval pour le champ d'id, mais pas dans QGIS 3 ?

**Comment by dsavary** [comment]
Oui c'est bien ça. Il n'y a peut être plus besoin de tout ce code pour QGIS 3

**Comment by gusthiot** [comment]
Inutile ?
Quand notre plugin crée un nouveau point, on n'a que sa géométrie à disposition. Il faut bin qu'on puisse avoir un moyen de remplir les champs des attributs... Ou alors la valeur par défaut s'inscrit...par défaut ?
J'ai commenté ce passage, tu peux tester et me dire comment cela réagit.

**Comment by dsavary** [comment]
toujours le même problème. 
La récupération des valeurs est différente que si on utilise un outil standard.
As-tu un environnement de test de ton côté ?

**Comment by gusthiot** [comment]
Mais il y a quand même une récupération de valeurs par défaut ?
Non pas, et je n'ai pas installé Postgre sur windows...

**Comment by dsavary** [comment]
non il ne récupère pas les attributs définit par défaut dans les propriétés de la couche.

Formulaire selon outil de création standard 

![form_vanne_standard](https://user-images.githubusercontent.com/6229296/74717663-122c7500-5231-11ea-8200-7c6ecdc77953.PNG)
 

Formulaire avec outil "interpolate"
![form_vanne_interpolate](https://user-images.githubusercontent.com/6229296/74717774-42741380-5231-11ea-8ffe-b7ca73767761.PNG)



Problème avec : 

- ID
- Précision planimétrique 
- Précision altimétrique
- Coord Z : On devrait avoir la valeur du z de la coordonnée

**Comment by gusthiot** [comment]
Et on l'avait précédemment, donc le petit code pour mettre les valeurs par défaut reste utile. Ne manque que le nextval...

**Comment by gusthiot** [comment]
J'ai remodifié un peu : donc en l'état actuel, si tu peux juste encore faire un test, cela fonctionne correctement sur QGIS 2, et sur QGIS 3 il y a juste le ID qui n'est pas accepté ainsi ?

**Comment by dsavary** [comment]
correct sur QGIS 2 
problème sur QGIS 3

**Comment by gusthiot** [comment]
J'ai peut-être trouvé un truc. Cela change qqch ?

**Comment by dsavary** [comment]
pour l'ID ça semble OK, mais pas pour la coordonnée Z de la géométrie .
Il devrait affiché le z interpolé et définir la précision altimétrique à "Précis"

![interpolate_default_value](https://user-images.githubusercontent.com/6229296/74738541-6d715e00-5257-11ea-9b4f-71b97c3cadb4.PNG)

**Comment by gusthiot** [comment]
C'est sûr que si je remplis les attributs avant d'ajouter la géométrie, cela risque effectivement de se produire...
Et maintenant ?

**Comment by dsavary** [comment]
Ah ouai ça va beaucoup mieux
Merci

**Comment by dsavary** [comment]
Petit bug avec Interpolate après plusieurs tests avec les utilisateurs.
J'ai bien un formulaire complet lors de la création d'un objet dans QGIS 3.
QGIS détecte bien qu'il y a une modification sur la couche. 
Lorsque j'enregistre, pas d'erreur. Tout va bien ! 
Mais en fait, je ne vois pas d'objets point apparaître sur la carte. 

L'enregistrement ne s'est pas fait correctement. Aucune commande INSERT et COMMIT envoyé à la BD. 
Je vais vérifier dans la BD. Aucun objet inséré !! 
Bizarre 

Si j'utilise un outil standard de QGIS core pour crééer une entité, aucun problème !

**Comment by gusthiot** [comment]
Tu me confirmes que cela fonctionne bien sur 2.18, mais pas sur 3 ?

**Comment by dsavary** [comment]
Oui avec 2.18 ça fonctionne

**Comment by gusthiot** [comment]
Cela joue maintenant ?

**Comment by dsavary** [comment]
C'est tout bon. Merci !
