### ISSUE TITLE
QGIS 3 VDLTools - intersect

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#44]
Erreur avec intersect
Certains sont identiques que pour "interpolate"

![image](https://user-images.githubusercontent.com/6229296/68943102-8a0a7f80-07aa-11ea-868f-60af3066d577.png)

**Comment by gusthiot** [comment]
Je dirais même plus, #43 et #44 sont la même erreur puisqu'ils appellent la même fonction dans finder.py. Corrigé.

**Comment by dsavary** [comment]
Erreur python lorsque l'outil INTERSECT est utilisé à l'intersection avec un polygone (ligne du bord du polygone) et le cercle defini. 

![image](https://user-images.githubusercontent.com/6229296/76032963-54e19300-5f3b-11ea-8d40-610ea8cf9930.png)


![image](https://user-images.githubusercontent.com/6229296/76032811-f9afa080-5f3a-11ea-8066-a6acad5abf75.png)

**Comment by gusthiot** [comment]
Cette erreur devrait être supprimée par l'application de #48.

**Comment by dsavary** [comment]
Oui effectivement ça devrait le corriger.
D'autre part, on rencontre aussi un problème d'accrochage sur l'outil "interpolate". Le calcul de l'intersection ne se fait pas toujours. Je n'arrive pas encore à bien reproduire ce problème. Ça n arrive pas toujours. C'est vraiment bizarre.
L'intersection ne se calcule pas avec l'outil interpolate mais parfois avec intersect. Je ne comprends pas.
Peut que c'est juste le symbole de snapping qui n'apparaît pas, J'en sais rien. 
J'espère que le ticket #48 règle tout ceci. :)

**Comment by dsavary** [comment]
Penses-tu pouvoir traiter ces tickets la semaine prochaine ?

**Comment by gusthiot** [comment]
> Oui effectivement ça devrait le corriger.
> D'autre part, on rencontre aussi un problème d'accrochage sur l'outil "interpolate". Le calcul de l'intersection ne se fait pas toujours. Je n'arrive pas encore à bien reproduire ce problème. Ça n arrive pas toujours. C'est vraiment bizarre.
> L'intersection ne se calcule pas avec l'outil interpolate mais parfois avec intersect. Je ne comprends pas.
> Peut que c'est juste le symbole de snapping qui n'apparaît pas, J'en sais rien.
> J'espère que le ticket #48 règle tout ceci. :)

A voir si on parle d'intersection avec un arc ou avec une droite...

**Comment by gusthiot** [comment]
> Penses-tu pouvoir traiter ces tickets la semaine prochaine ?

Normalement oui. 
Tu écris à des heures étranges ici....

**Comment by gusthiot** [comment]
> 
> 
> Erreur python lorsque l'outil INTERSECT est utilisé à l'intersection avec un polygone (ligne du bord du polygone) et le cercle defini.
> 
> ![image](https://user-images.githubusercontent.com/6229296/76032963-54e19300-5f3b-11ea-8d40-610ea8cf9930.png)
> 
> ![image](https://user-images.githubusercontent.com/6229296/76032811-f9afa080-5f3a-11ea-8066-a6acad5abf75.png)

Corrigé

**Comment by gusthiot** [comment]
> 
> 
> Oui effectivement ça devrait le corriger.
> D'autre part, on rencontre aussi un problème d'accrochage sur l'outil "interpolate". Le calcul de l'intersection ne se fait pas toujours. Je n'arrive pas encore à bien reproduire ce problème. Ça n arrive pas toujours. C'est vraiment bizarre.
> L'intersection ne se calcule pas avec l'outil interpolate mais parfois avec intersect. Je ne comprends pas.
> Peut que c'est juste le symbole de snapping qui n'apparaît pas, J'en sais rien.
> J'espère que le ticket #48 règle tout ceci. :)

Sans ma "snap curved", cela change qqch ?

**Comment by dsavary** [comment]
c'est tout bon. merci !
