### ISSUE TITLE
QGIS 3 VDLTools - profil tools

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#46]
Si les altitudes ne sont pas cohérents entre les points et la ligne de profil, j'obtiens cette erreur sur l'outil de profil.
![error_profiltools_vdltools](https://user-images.githubusercontent.com/6229296/74134939-acfed100-4beb-11ea-97ae-24c635dff0b7.PNG)

**Comment by gusthiot** [comment]
Corrigé (un oubli dans le passage qgis2 -> qgis3)

**Comment by dsavary** [comment]
toujours la même erreur à la même ligne 

if self.__rubberSit.numberOfVertices() == 0:
                    self.__rubberSit.setToGeometry(QgsGeometry().fromPointXY(point), None)
else:

**Comment by gusthiot** [comment]
Donc "QsgGeometry has no attribute fromPointXY" ?

**Comment by gusthiot** [comment]
Il y avait une double faute à la base (fromPoint->fromPointXY et point = QgsPoint->QgsPointXY)
Corrigé

**Comment by dsavary** [comment]
Quand on clique sur "appliquer l'altitude du point à la ligne" on obtient cette erreur : 

![error_profiltools_vdltools_apres_correction](https://user-images.githubusercontent.com/6229296/74520379-b653aa80-4f17-11ea-8cb1-353ac6abb1e6.PNG)

**Comment by gusthiot** [comment]
corrigé

**Comment by dsavary** [comment]
magnifique ! 
petite traduction manquante lors de l'interpolation 
![error_profiltools_vdltools_traduction](https://user-images.githubusercontent.com/6229296/74633648-60bf0e00-5162-11ea-880e-34610a716aca.PNG)

**Comment by gusthiot** [comment]
J'ai fait une mise à jour des traductions :)

**Comment by dsavary** [comment]
ok merci
