### ISSUE TITLE
QGIS 3 : intégration de VDLNetwork "control tool"

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#47]
Lors du paramétrage du plugin (définir la BD, la schéma et la table de contrôle), j'obtiens cette erreur : 

![error_vdltools_parametres_control](https://user-images.githubusercontent.com/6229296/74520631-3f6ae180-4f18-11ea-82be-d3bf36e6078b.PNG)

**Comment by gusthiot** [comment]
corrigé

**Comment by dsavary** [comment]
est-ce qu'il serait possible d'avoir une boite de dialogue des paramètres avec une barre coulissante et qui peut se rétrécir, car je ne peux saisir les paramètres de l'outil de contrôle "inatteignable"

![error_vdltools_parametres_control_barre_coulissante](https://user-images.githubusercontent.com/6229296/74634820-f8256080-5164-11ea-8051-73a91eca0d77.PNG)

et du coup aussi pour la boîte de dialogue qui affiche la liste des contrôles.

Sinon erreur de QmessageBar 

![error_vdltools_control_warning](https://user-images.githubusercontent.com/6229296/74634796-e93eae00-5164-11ea-8653-5ac0f8c2ee8c.PNG)

Pour t'aider un peu :) 
 level=Qgis.Critical, duration=5)

**Comment by gusthiot** [comment]
Erreur corrigée.
J'ai ajouté le scroll pour les paramètres, dans la 2.18 aussi pour la peine.

**Comment by dsavary** [comment]
Ah ouai c'est plus pratique quand même. 
Je n'arrive pas à dessiner la zone de contrôle. J'ai chaque fois ce message dans la bandeau de QGIS. 

![error_vdltools_control_area](https://user-images.githubusercontent.com/6229296/74716995-e0ff7500-522f-11ea-8ffe-378c68d7abb6.PNG)

**Comment by gusthiot** [comment]
Seulement dans QGIS 3 ?

**Comment by dsavary** [comment]
sur QGIS 2 c'est une autre erreur : 

![scroll_control_tool](https://user-images.githubusercontent.com/6229296/74718173-f7a6cb80-5231-11ea-9d3e-00212ff918d8.PNG)

**Comment by gusthiot** [comment]
Oups...ça devrait être bon pour tester sur QGIS 2

**Comment by dsavary** [comment]
même problème sur QGIS 2, impossible de créer la zone de contrôle

**Comment by gusthiot** [comment]
Ah, j'ai trouvé le bug. Corrigé

**Comment by dsavary** [comment]
c'est ok

**Comment by dsavary** [comment]
sur QGIS 3 j'ai ça : 

![error_vdltools_control](https://user-images.githubusercontent.com/6229296/74737911-1e76f900-5256-11ea-8725-632ca9a045ee.PNG)


De plus, il ne semble pas bien interpréter les attributs active (true ou false) et check_defaut (true ou false) de la table qui listent les contrôles.
Si active = true, le contrôle est visible dans la liste
Si defaut = true, le contrôle est coché par defaut

![list_control_non coche](https://user-images.githubusercontent.com/6229296/74738178-a826c680-5256-11ea-909a-43947ffe1115.PNG)

**Comment by gusthiot** [comment]
J'ai corrigé l'erreur.
Tu entends quoi par : pas bien interpréter ?

**Comment by dsavary** [comment]
Je devrais avoir des coches partout sur la boite de dialogue étant donnée que j'ai la valeur true dans la table qui liste les contrôles. L'info n'est pas lu correctement dans la BD.

**Comment by gusthiot** [comment]
Je me demandais pourquoi le true du active semblait être bien interprété, mais pas celui du defaut. C'est parce que le active est testé avec QgsFeatureRequest().setFilterExpression('"active" is true') qui semble toujours ok, alors que defaut est testé avec if self.__listReq[i].get("check") == 't', qui peut ne plus être consistant.
Tu peux tester ma dernière et me donner la sortie console Python ?

**Comment by dsavary** [comment]
Dans plusieurs petits scripts python2 ,j'ai changé =='t' en == True (python 3)

**Comment by gusthiot** [comment]
Ha, j'ai modifié, ça fonctionne ?

**Comment by dsavary** [comment]
ça fonctionne nickel 
merci
