### ISSUE TITLE
Créer des "Readme" pour chaque outil du plugin VDL 

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#5]
le readme doit expliquer de manière général le fonctionnement de chaque outil du plugin "VDL tools".
Il devrait servir de documentation pour les utilisateurs.

**Comment by gusthiot** [comment]
Première édition terminée

**Comment by dsavary** [comment]
Détailler plus spécifiquement le fonctionnement (chaque étape et possibilité) de l'outil afin que cette documentation serve de base aux utilisateurs.
Élaborer des "gif" animés montrant la manière d'utiliser chaque outil.

**Comment by gusthiot** [comment]
Assez détaillé ?

**Comment by gusthiot** [comment]
Gifs ajoutés à la page de présentation. Manque-t-il quelque chose ?
