### ISSUE TITLE
Fonctionnement possible avec plusieurs types de géométrie

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#8]
L'outil "Move and copy" devrait pouvoir fonctionner avec les géométries 2D et 3D de type : point, polyligne, polygone, et si possible :  polyligne avec courbes, polygone avec courbes.
L'outil "Duplicate" avec les géométries : polyligne, polygone, et si possible :  polyligne avec courbes, polygone avec courbes.

**Comment by gusthiot** [comment]
fait pour compoundcurve et curvepolygon
