### ISSUE TITLE
Symbole de l'accrochage "intersect" plus visible (croix avec bords plus large)

### ISSUE THREAD

**Issue by dsavary** [gusthiot/VDLTools#9]

**Comment by gusthiot** [comment]
Fait. A tester

**Comment by dsavary** [comment]
Problème d'activation de l'outil  , notamment sur des couches en 3D (POSTGIS)
erreur suivante : 
AttributeError: 'NoneType' object has no attribute 'snapToIntersection' 
Traceback (most recent call last):
  File "C:/Users/cada0093/.qgis2/python/plugins\VDLTools\tools\intersect_tool.py", line 195, in canvasMoveEvent
    snappedIntersection = Finder.snapToIntersection(mouseEvent.pos(), self, self.__layerList)
AttributeError: 'NoneType' object has no attribute 'snapToIntersection'
